version: "3.9"
services:
  application:
    image: open-project:latest
    depends_on:
      - postgres
    ports:
      - "8082:8082"
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"